title: Comisión de Jubilados
description: Sitio web oficial para jubilados
url: "https://hfmd26.github.io" # O tu dominio en GitHub Pages
baseurl: "" # Deja esto en blanco si es repositorio tipo usuario.github.io

remote_theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Hector
  avatar: "/assets/images/avatar.png" # puedes eliminar esta línea si no usas imagen
  bio: "Página de gestión y documentación para jubilados"

# Navegación
header_pages:
  - index.md
  - about.markdown
  - miembros.md
  - reportes.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
