remote_theme: pages-themes/cayman

# Metadata general
title: Comisión de Jubilados
description: Sitio oficial informativo
domain: hfmd26.github.io
url: "https://hfmd26.github.io"
baseurl: "" # No colocar / al final

# Plugins requeridos por minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Menú principal
header_pages:
  - index.md
  - miembros.md
  - procedimientos.md
  - entrega.md
  - reportes.md
  - actividades.md

# Ajustes de visual
locale: "es-MX"
logo: "/assets/images/logo.jpg"
author:
  name   : Comisión de Jubilados
  avatar : "/assets/images/avatar.png"
  bio    : "Bienvenidos al portal oficial"

# Defaults para páginas
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      sidebar:
        nav: "main"

# Navegación lateral (si deseas mostrarla)
navigation:
  main:
    - title: "Inicio"
      url: /
    - title: "Lista de miembros"
      url: /miembros/
    - title: "Procedimientos y formatos"
      url: /procedimientos/
    - title: "Entrega y Recepción"
      url: /entrega/
    - title: "Reportes"
      url: /reportes/
    - title: "Actividades"
      url: /actividades/

header:
  overlay_title: false
